language: python

python:
  - "3.7"

matrix:
  fast_finish: true

sudo: false
dist: bionic

jobs:
  include:
    - name: lints
      install:
        - pip install black
        - pip install pylint
      script:
        - black --check -l 120 .
    - name: tests
      addons:
        apt:
          sources:
            - sourceline: 'ppa:maarten-fonville/protobuf'
          packages:
            - libsodium-dev
            - libprotobuf-dev
            - protobuf-compiler
      install: pip install --no-binary=protobuf protobuf pysodium requests websocket
      script: python -m unittest
